name: Manual Publishing - Azure App Service - OpenSourceExplorer(Production), Build and deploy DotnetCore app

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-build

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: OpenSourceExplorer
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DA2734CE5E554878B380103F30423AC8 }}
        package: ${{env.DOTNET_ROOT}}/myapp
